services:
  mixmover:
    container_name: mixmover
    image: ghcr.io/matterladd/mix-mover:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./server/.env
    volumes:
      # ! Make sure this directory has the right perms to be accessed, otherwise DB will not be created/found
      - ./server/data:/app/server/data
    ports:
      - "8000:8000"
