name: Check GHCR Permissions

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: matterladd/mix-mover

permissions:
  contents: read
  packages: write

jobs:
  check:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push a tiny test tag
        run: |
          docker pull alpine:latest
          docker tag alpine:latest ghcr.io/${{ env.IMAGE_NAME }}:permtest
          docker push ghcr.io/${{ env.IMAGE_NAME }}:permtest
